// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MpdcViewExtentions;
using UIKit;

namespace Izrune.iOS
{
	public partial class ExamResultViewController : UIViewController
	{
		public ExamResultViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("ExamResultStoryboardId");

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InitUI();
        }

        private void InitUI()
        {
            pointView.AddShadowToView(4, 50, 0.8f, UIColor.FromRGBA(0, 0, 0, 0.35f));
            timeShadowView.AddShadowToView(4, 50, 0.8f, UIColor.FromRGBA(0, 0, 0, 0.35f));
        }
    }
}
