// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MpdcViewExtentions;
using UIKit;

namespace Izrune.iOS
{
	public partial class QuestionImageViewController : UIViewController
	{
		public QuestionImageViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("QuestionImageStoryboardId");

        public string ImageUrl;

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            this.View.BackgroundColor = UIColor.Clear;
            this.DefinesPresentationContext = true;
            this.ModalPresentationStyle = UIModalPresentationStyle.OverCurrentContext;

            questionImageView.InitImageFromWeb(ImageUrl, false, false);

            closeBtn.TouchUpInside += delegate {
                CloseVc();
            };
        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            UIView.Animate(1, () => {

                this.mainBgView.BackgroundColor = UIColor.FromRGBA(0, 0, 0, 50);
            });
        }

        private void CloseVc()
        {
            UIView.Animate(0.5f, () => mainBgView.BackgroundColor = UIColor.FromRGBA(0, 0, 0, 0), () => DismissViewController(true, null));
        }
    }
}
