// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using XLPagerTabStrip;

namespace Izrune.iOS
{
	public partial class QuestionResultViewController : UIViewController, IIndicatorInfoProvider
    {
		public QuestionResultViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("QuestionResultStoryboardId");

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        public IndicatorInfo IndicatorInfoForPagerTabStrip(PagerTabStripViewController pagerTabStripController)
        {
            return new IndicatorInfo("კითხვები");
        }
    }
}
