// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using IZrune.PCL.Abstraction.Models;
using UIKit;
using XLPagerTabStrip;

namespace Izrune.iOS
{
	public partial class ResultTabbedViewController : ButtonBarPagerTabStripViewController, IPagerTabStripDelegate
    {
		public ResultTabbedViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("ResultTabbedStoryboardId");

        private List<UIViewController> TabVcs = new List<UIViewController>();

        public IQuisInfo QuisInfo;

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var barButton = new UIBarButtonItem(UIBarButtonSystemItem.Action, null)
            {
                Title = "გაზიარება"
            };

            barButton.Clicked += delegate {
                //TODO
            };
            this.NavigationItem.RightBarButtonItem = barButton;

        }

        public override UIViewController[] CreateViewControllersForPagerTabStrip(PagerTabStripViewController pagerTabStripViewController)
        {
            return TabVcs.ToArray();
        }
    }
}
