// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Izrune.iOS.CollectionViewCells;
using MPDCiOSPages.ViewControllers;
using UIKit;
using FPT.Framework.iOS.UI.DropDown;

namespace Izrune.iOS
{
	public partial class TestResultsViewController : BaseViewController, IUICollectionViewDelegate, IUICollectionViewDataSource, IUICollectionViewDelegateFlowLayout
	{
		public TestResultsViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("TestResultsStoryboardId");

        DropDown YearDropDown = new DropDown();
        DropDown MonthDropDown = new DropDown();


        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InitCollectionViewSettings();

            resultCollectionView.ReloadData();
        }

        private void InitCollectionViewSettings()
        {
            resultCollectionView.RegisterNibForCell(ResultCollectionViewCell.Nib, ResultCollectionViewCell.Identifier);
            resultCollectionView.Delegate = this;
            resultCollectionView.DataSource = this;
        }

        public nint GetItemsCount(UICollectionView collectionView, nint section)
        {
            return 10;
        }

        public UICollectionViewCell GetCell(UICollectionView collectionView, NSIndexPath indexPath)
        {
            var resultCell = resultCollectionView.DequeueReusableCell(ResultCollectionViewCell.Identifier, indexPath) as ResultCollectionViewCell;

            return resultCell;
        }


        [Export("collectionView:layout:sizeForItemAtIndexPath:")]
        public CoreGraphics.CGSize GetSizeForItem(UICollectionView collectionView, UICollectionViewLayout layout, NSIndexPath indexPath)
        {
            return new CoreGraphics.CGSize(collectionView.Frame.Width, 210);
        }
    }
}
