// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Izrune.iOS
{
	public partial class FooterTestView : UICollectionReusableView
	{

        public UIButton SkipBtn { get => skipBtn; }

        public FooterTestView (IntPtr handle) : base (handle)
		{
		}
	}
}
