// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Izrune.iOS
{
	public partial class TestScrollViewController : UIViewController
	{
		public TestScrollViewController (IntPtr handle) : base (handle)
		{
		}

	}
}
