// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MessageUI;
using MpdcViewExtentions;
using UIKit;

namespace Izrune.iOS
{
	public partial class ContactViewController : UIViewController, IUINavigationControllerDelegate
	{
		public ContactViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("ContactViewControllerStoryboardId");

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            InitUI();

            AddGesture(phoneView, "tel://+995577683232");
            //AddGesture(mailView, "info@izrune.ge/");
            AddGesture(facebookView, "https://www.facebook.com/izrune.ge");

            if(mailView.GestureRecognizers == null || mailView.GestureRecognizers?.Length == 0)
            {
                mailView.AddGestureRecognizer(new UITapGestureRecognizer(() =>
                {
                    string mailUrl = "info@izrune.ge";
                    string subject = "";
                    string body = "";
                    using (var encoded = new NSString($"mailto:{mailUrl}?subject={subject}&body={body}").CreateStringByAddingPercentEscapes(NSStringEncoding.UTF8))
                    using (var url = NSUrl.FromString(encoded))
                    {
                        UIApplication.SharedApplication.OpenUrl(url);
                    }
                }));
            }
        }


        private void InitUI()
        {
            phoneView.ToCardView(26, 3, 0.2f, UIColor.Black);
            mailView.ToCardView(26, 3, 0.2f, UIColor.Black);
            facebookView.ToCardView(26, 3, 0.2f, UIColor.Black);
        }

        private void InitGestures()
        {
            if(phoneView.GestureRecognizers == null || phoneView.GestureRecognizers?.Length == 0)
            {
                phoneView.AddGestureRecognizer(new UITapGestureRecognizer(() => {
                    var number = NSUrl.FromString("tel://+995577683232");
                    UIApplication.SharedApplication.OpenUrl(number);
                }));
            }
        }

        private void AddGesture(UIView _view, string url)
        {

            _view.AddGestureRecognizer(new UITapGestureRecognizer(() =>
            {
                var Url = new NSUrl(url);

                try
                {
                    if (UIApplication.SharedApplication.CanOpenUrl(Url))
                        UIApplication.SharedApplication.OpenUrl(Url);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }));
        }
    }
}
