// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MpdcViewExtentions;
using System.Linq;
using Izrune.iOS.Utils;

namespace Izrune.iOS
{
	public partial class EditProfileViewController : UIViewController
	{
		public EditProfileViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("EditProfileStoryboardId");

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();


            View.LayoutIfNeeded();

            InitUI();
        }

        private void InitUI()
        {
            //var views = editStackView.Subviews.ToList();

            //foreach (var item in views)
            //{
            //    item.Layer.BorderWidth = 3;
            //    item.Layer.BorderColor = UIColor.White.CGColor;
            //    item.Layer.CornerRadius = 25;
            //    item.
            //}


            initView(parentView, parentShadow);
            initView(studentView, studentShadow);
            initView(passowrdView, passwordShadow);

            addStudentBtn.Layer.CornerRadius = 25;
        }

        private void initView(UIView view, UIView viewForShadow)
        {
            view.Layer.BorderWidth = 3;
            view.Layer.BorderColor = UIColor.White.CGColor;
            view.Layer.CornerRadius = 25;
            view.ApplyGradient(AppColors.PurpleGradient);

            viewForShadow.AddShadowToView(10, 25, 0.8f, AppColors.TitleColor);
        }
    }
}
