// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using IZrune.PCL.Abstraction.Services;
using UIKit;

namespace Izrune.iOS
{
	public partial class MoreInfoViewController : UIViewController
	{
		public MoreInfoViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("MoreInfoViewControllerStoryboardId");


        public string HtmlString { get; set; }

        public async override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var newsService = ServiceContainer.ServiceContainer.Instance.Get<INewsService>();
            try
            {
                if(Plugin.Connectivity.CrossConnectivity.Current.IsConnected)
                {
                    var data = await newsService.GetMoreInfoAsync();

                    infoWebView.LoadHtmlString(data, NSUrl.FromString("https://www.google.com/"));
                }
                else
                {
                    var alertVc = UIAlertController.Create("ყურადღება!", "შეამოწმეთ ინტერნეტთან კავშირი", UIAlertControllerStyle.Alert);
                    alertVc.AddAction(UIAlertAction.Create("დახურვა", UIAlertActionStyle.Default, null));
                    this.PresentViewController(alertVc, true, null);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

        }
    }
}
