// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Izrune.iOS
{
	public partial class MoreInfoViewController : UIViewController
	{
		public MoreInfoViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("MoreInfoViewControllerStoryboardId");


        public string HtmlString { get; set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            //infoWebView.LoadHtmlString(HtmlString, NSUrl.FromString("https://www.google.com/"));
        }
    }
}
