// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using IZrune.PCL.Abstraction.Services;
using UIKit;

namespace Izrune.iOS
{
	public partial class MoreInfoViewController : UIViewController
	{
		public MoreInfoViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("MoreInfoViewControllerStoryboardId");


        public string HtmlString { get; set; }

        public async override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var newsService = ServiceContainer.ServiceContainer.Instance.Get<INewsService>();

            var data = await newsService.GetMoreInfoAsync();

            infoWebView.LoadHtmlString(data, NSUrl.FromString("https://www.google.com/"));
        }
    }
}
