// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Izrune.iOS
{
	public partial class StatisticViewController : UIViewController
	{
		public StatisticViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
