// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Izrune.iOS
{
	public partial class UpdatePacketViewController : UIViewController
	{
		public UpdatePacketViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("UpdatePacketStoryboardId");
    }
}
