// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MpdcViewExtentions;
using IZrune.PCL.Helpers;
using IZrune.PCL.Abstraction.Models;

namespace Izrune.iOS
{
	public partial class ChangePasswordViewController : UIViewController
	{
		public ChangePasswordViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("ChangePasswordStoryboardId");
        private IParent user;

        public async override void ViewDidLoad()
        {
            base.ViewDidLoad();

            user = await UserControl.Instance.GetCurrentUser();

            InitUI();

            InitGestures();
        }

        private void InitGestures()
        {
            saveBtn.TouchUpInside += async delegate
            {
                if(CheckPassword())
                {

                }

                else
                {

                }
            };

            backBtn.TouchUpInside += delegate {

                this.NavigationController.PopViewController(true);
            };
        }

        private void InitUI()
        {
            InitTF(oldPassTf, oldPassView);
            InitTF(passwordNewTf, passNewView);
            InitTF(repeatNewPasswordTf, repeatNewPassView);

            backBtn.Layer.CornerRadius = 25;
            saveBtn.Layer.CornerRadius = 25;
        }

        private void InitTF(UITextField textField, UIView view)
        {
            textField.Layer.BorderWidth = 2;
            textField.Layer.BorderColor = UIColor.White.CGColor;

            textField.MakeRoundedTextField(25, UIColor.FromRGB(243,243,243), 20);
            view.AddShadowToView(3, 25, 0.3f, UIColor.FromRGBA(0, 0, 0, 0.25f));
        }

        private bool CheckPassword()
        {
            return (passwordNewTf.Text == repeatNewPasswordTf.Text);
        }

        private void ShowAlert()
        {
            var alertVc = UIAlertController.Create("ყურადღება!", "პაროლი წარმატებით შეიცვალა", UIAlertControllerStyle.Alert);
            alertVc.AddAction(UIAlertAction.Create("დახურვა", UIAlertActionStyle.Default, null));
            this.PresentViewController(alertVc, true, null);
        }
    }
}
