// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Foundation;
using Izrune.iOS.CollectionViewCells;
using IZrune.PCL.Abstraction.Models;
using IZrune.PCL.Abstraction.Services;
using IZrune.PCL.Helpers;
using IZrune.PCL.Implementation.Models;
using MPDCiOSPages.ViewControllers;
using UIKit;

namespace Izrune.iOS
{
	public partial class DiplomeViewController : BaseViewController, IUICollectionViewDelegate, IUICollectionViewDataSource, IUICollectionViewDelegateFlowLayout
	{
		public DiplomeViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("DiplomeStoryboardId");

        public IStudent Student;
        private IStatisticServices diplomeService;
        private List<IStudentsStatistic> StudentsStatistics;

        private ExamResultViewController diplomeDetailVc;

        public async override void ViewDidLoad()
        {
            base.ViewDidLoad();

            this.NavigationItem.BackBarButtonItem = new UIBarButtonItem("", UIBarButtonItemStyle.Plain, null);

            InitUI();

            await LoadDataAsync();

            InitCollectionViewSettings();

            diplomeDetailVc = Storyboard.InstantiateViewController(ExamResultViewController.StoryboardId) as ExamResultViewController;
            diplomeDetailVc.Student = Student;

            backBtn.TouchUpInside += delegate {
                this.NavigationController.PopViewController(true);

            };
        }

        private void InitUI()
        {
            viewForDropDown.Layer.CornerRadius = 20;
        }

        public async Task LoadDataAsync()
        {
            HideHeader(true);
            ShowLoading();


            diplomeService = ServiceContainer.ServiceContainer.Instance.Get<IStatisticServices>();

            StudentsStatistics = (await diplomeService.GetStudentStatisticsAsync(IZrune.PCL.Enum.QuezCategory.QuezExam))?.Where(x => x.DiplomaUrl != null)?.ToList();

            if (StudentsStatistics == null || StudentsStatistics?.Count == 0)
            {
                HideHeader(true);
                ShowAlert();
            }
            else
                HideHeader(false);
            EndLoading();
        }

        private void HideHeader(bool hide)
        {
            headerImageView.Hidden = hide;
            headerLbl.Hidden = hide;
            viewForDropDown.Hidden = hide;
        }

        private void ShowAlert()
        {
            var alert = UIAlertController.Create("შეცდომა", "ინფორმაცია ვერ მოიძებნა.", UIAlertControllerStyle.Alert);
            alert.AddAction(UIAlertAction.Create("დახურვა", UIAlertActionStyle.Default, null));
            this.PresentViewController(alert, true, () => { this.NavigationController.PopViewController(true); });
        }

        public nint GetItemsCount(UICollectionView collectionView, nint section)
        {
            return StudentsStatistics?.Count ?? 0;
        }

        public UICollectionViewCell GetCell(UICollectionView collectionView, NSIndexPath indexPath)
        {
            var cell = diplomeCollectionView.DequeueReusableCell(DiplomeCollectionViewCell.Identifier, indexPath) as DiplomeCollectionViewCell;

            var data = StudentsStatistics?[indexPath.Row];

            cell.CellClicked = async (studentStatistic) =>
            {
                ShowLoading();

                var quisInfo = await UserControl.Instance.GetQuisInfo(studentStatistic.Id);

                diplomeDetailVc.QuisInfo = quisInfo;

                EndLoading();

                this.NavigationController.PushViewController(diplomeDetailVc, true);
            };

            cell.InitData(data);

            return cell;
        }

        private void InitCollectionViewSettings()
        {
            diplomeCollectionView.RegisterNibForCell(DiplomeCollectionViewCell.Nib, DiplomeCollectionViewCell.Identifier);

            diplomeCollectionView.Delegate = this;
            diplomeCollectionView.DataSource = this;
        }

        [Export("collectionView:layout:sizeForItemAtIndexPath:")]
        public CoreGraphics.CGSize GetSizeForItem(UICollectionView collectionView, UICollectionViewLayout layout, NSIndexPath indexPath)
        {
            return new CoreGraphics.CGSize(collectionView.Frame.Width * 0.45, 50);
        }
    }
}
