// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using IZrune.PCL.Abstraction.Models;
using UIKit;
using MpdcViewExtentions;
using System.Globalization;
using MPDC.iOS.Utils;

namespace Izrune.iOS
{
	public partial class NewsDetailViewController : UIViewController, IUIWebViewDelegate
	{
		public NewsDetailViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("NewsDetailStoryboardId");

        public INews News;

        CultureInfo cultureInfo = new CultureInfo("ka-GE");

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            newsWebView.Delegate = this;
            newsWebView.ScrollView.ScrollEnabled = false;

            InitUI();

        }

        private void InitUI()
        {
            newsImageView.Layer.CornerRadius = 10;
            newsImageView.InitImageFromWeb(News?.ImageUrl, false, false);

            newstitleLbl.Text = News?.Title;
            newsDateLbl.Text = News?.date.ToString("dd MMMM yyyy", cultureInfo);

            string bpgNpStyle = "@font-face {font-family: MyFont;src: url(\"bpg_mrgvlovani_2010.ttf\")}"; 
            var fontPath = bpgNpStyle;
            var content = News?.Content.Replace("font-size", "width");
            content = content.Replace("max-height", "width");
            content = content.Replace("h1", "p");

            string htmlContent = $@"<html><head><style> *{"{ margin-left: 0px!important;background-color:rgba(0, 0, 0, 0)!important;background:rgba(0, 0, 0, 0)!important;max-height:none!important; margin-right: 0px!important; padding-left : 0px!important; padding-right : 0px!important; width: 100%!important;height:auto!important;}"} iframe{{ margin-left : 0px!important; margin-right : 0px!important; margin-top : 0px!important; margin-bottom : 0px!important;}} {"td{width: 50%!important; text-align:left!important; height: auto!important; }"} div{"{text-align: left!important;}"} span,p,a,div {$"{"{"}text-align: left!important;background-color:rgba(0, 0, 0, 0)!important;background:rgba(0, 0, 0, 0)!important;font-family:MyFont!important;)!important;{"}"}"} </style></head><body style={"\""}padding:0px;margin:0px{"\""}><div id='mainDiv'>{"<p>" + News?.Content + "</p>"}</div></body></html>";
            newsWebView.LoadHtmlString(htmlContent, NSUrl.FromString("https://www.google.com/"));
        }

        [Export("webViewDidFinishLoad:")]
        public void LoadingFinished(UIWebView webView)
        {
            var height = News?.Title.GetStringHeight((float)newsImageView.Frame.Width, 0, 12);

            var webviewHeight = webView.ScrollView.ContentSize.Height;

            var headerHeight = 225 + 25 + height + webviewHeight;

            contentViewHeight.Constant = (System.nfloat)headerHeight;
        }

        [Export("webView:shouldStartLoadWithRequest:navigationType:")]
        public bool ShouldStartLoad(UIWebView webView, NSUrlRequest request, UIWebViewNavigationType navigationType)
        {
            if(navigationType == UIWebViewNavigationType.LinkClicked)
            {
                bool isUri = Uri.IsWellFormedUriString(request.Url.ToString(), UriKind.RelativeOrAbsolute);

                if (request.Url.ToString().Contains("http"))
                {
                    var url = request.Url;

                    UIApplication.SharedApplication.OpenUrl(url);
                }
                else
                {
                    var url = request.Url;

                    UIApplication.SharedApplication.OpenUrl(url);
                }

                return false;
            }

            return true;
        }
    }
}
