// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Izrune.iOS
{
	public partial class NewsViewController : UIViewController
	{
		public NewsViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboadrId = new NSString("NewsViewControllerStoryboardId");
    }
}
