// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using IZrune.PCL.Abstraction.Models;
using UIKit;

namespace Izrune.iOS
{
	public partial class PaymentMethodViewController : UIViewController
	{
		public PaymentMethodViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("PaymentMethodStoryboardId");
        private PaymentViewController paymentVc;
        public string PaymentUrl { get; set; }

        public IPay PayInfo { get; set; }

        public Action GoToLogin { get; set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            paymentVc = Storyboard.InstantiateViewController(PaymentViewController.StoryboardId) as PaymentViewController;
            paymentVc.PayInfo = PayInfo;

            InitGestures();

            paymentVc.GoToLogin = () => { GoToLogin?.Invoke(); };
        }

        private void InitGestures()
        {
            payViaBankBtn.TouchUpInside += delegate {
                PaymentUrl = "https://www.youtube.com/";
                GoToPayment();
            };

            payViaCardBtn.TouchUpInside += delegate {
                GoToPayment();
            };

            payViaPayBoxBtn.TouchUpInside += delegate {
                PaymentUrl = "http://www.izrune.ge/images/tbcpay_image2.png";
                GoToPayment();
            };
        }

        private void GoToPayment()
        {
            this.NavigationController.PushViewController(paymentVc, true);
        }
    }
}
