// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Izrune.iOS
{
	public partial class PaymentMethodViewController : UIViewController
	{
		public PaymentMethodViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("PaymentMethodStoryboardId");
        private PaymentViewController paymentVc;
        public string PaymentUrl { get; set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            paymentVc = Storyboard.InstantiateViewController(PaymentViewController.StoryboardId) as PaymentViewController;
            paymentVc.PaymentUrl = PaymentUrl;

            InitGestures();
        }

        private void InitGestures()
        {
            payViaBankBtn.TouchUpInside += delegate {
                GoToPayment();
            };

            payViaCardBtn.TouchUpInside += delegate {
                GoToPayment();
            };

            payViaPayBoxBtn.TouchUpInside += delegate {
                GoToPayment();
            };
        }

        private void GoToPayment()
        {
            this.NavigationController.PushViewController(paymentVc, true);
        }
    }
}
