// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using IZrune.PCL.Abstraction.Models;
using UIKit;

namespace Izrune.iOS
{
	public partial class PaymentViewController : UIViewController, IUIWebViewDelegate
	{
		public PaymentViewController (IntPtr handle) : base (handle)
		{
		}

        public string PaymentUrl;

        public IPay PayInfo { get; set; }

        public static readonly NSString StoryboardId = new NSString("PaymentStoryboardId");

        public Action GoToLogin { get; set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            paymentWebView.Delegate = this;

            if(PayInfo.CurrentUserPayURl != null)
            {
                var nsUrl = NSUrl.FromString(PayInfo?.CurrentUserPayURl);
                var request = new NSUrlRequest(nsUrl);
                paymentWebView.LoadRequest(request);
            }
        }

        [Export("webView:shouldStartLoadWithRequest:navigationType:")]
        public bool ShouldStartLoad(UIWebView webView, NSUrlRequest request, UIWebViewNavigationType navigationType)
        {
            if(request.Url.AbsoluteString == PayInfo.SuccesUrl)
            {
                //TODO
                GoToLogin?.Invoke();
            }

            else if(request.Url.AbsoluteString == PayInfo.FailUrl)
            {
                //TODO
                GoToLogin?.Invoke();
            }

            else if(request.Url.AbsoluteString == "http://www.izrune.ge/")
            {
                GoToLogin?.Invoke();
            }
            return true;
        }

    }
}
