// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using Foundation;
using IZrune.PCL.Abstraction.Models;
using MpdcViewExtentions;
using UIKit;

namespace Izrune.iOS
{
	public partial class PayViaBankViewController : UIViewController
	{
		public PayViaBankViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("PayViaBankStoryboardId");

        public IParent CurrentUser;

        public IPrice SelectedPrice;

        public string UserName { get; set; }
        public int allPrices { get; private set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            allPrices = IZrune.PCL.Helpers.UserControl.Instance.GetAllPackagePrice();

            InitDataAsync();

            var barButton = new UIBarButtonItem(UIBarButtonSystemItem.Action, null);

            barButton.Clicked += delegate {
                var url = $"მიმღები: შპს \"ეტალონი-განათლება\" მიმღების საიდენტიფიკაციო კოდი: 404561979 სს ბანკი \"თიბისი ბანკი\" TBCBGE22 ანგარიშის ნომერი: GE82TB7994 6360 8010 0007 www.izrune.ge თარიღი: {DateTime.Now.ToString("dd/MM/yyyy")}";

                if (!string.IsNullOrEmpty(url) && !string.IsNullOrWhiteSpace(url))
                {
                    this.ShareUrl(url);
                }
            };

            this.NavigationItem.RightBarButtonItem = barButton;

            numberCopyBttn.TouchUpInside += delegate {
                UIPasteboard.General.String = "GE82TB7994636080100007";
                numberCopyBttn.SetTitle("ნომერი დაკოპირებულია", UIControlState.Normal);
            };
        }

        private void InitDataAsync()
        {
            try
            {
               
                if(CurrentUser == null)
                {
                    profileNumberView.Hidden = true;

                    userNameLbl.Text = $"1. მომხმარებელი: {UserName}";
                    billLbl.Text = $"2. გადასახდელი თანხა - {allPrices} ლარი";
                    dateLbl.Text = DateTime.Now.ToString("dd/MM/yyyy");
                }
                else
                {
                    profileNumberLbl.Text = $"1. პროფილის ნომერი - {CurrentUser?.ProfileNumber}";
                    userNameLbl.Text = $"2. მომხმარებელი: {CurrentUser?.Name + " " + CurrentUser?.LastName}";
                    billLbl.Text = $"3. გადასახდელი თანხა - {SelectedPrice?.price} ლარი";
                    dateLbl.Text = DateTime.Now.ToString("dd/MM/yyyy");
                }
                
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
    }
}
