// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using Foundation;
using IZrune.PCL.Abstraction.Models;
using MpdcViewExtentions;
using UIKit;

namespace Izrune.iOS
{
	public partial class PayViaBankViewController : UIViewController
	{
		public PayViaBankViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("PayViaBankStoryboardId");
        private IParent CurrentUser;
        public IPrice SelectedPrice;

        public async override void ViewDidLoad()
        {
            base.ViewDidLoad();

            await InitDataAsync();

            var barButton = new UIBarButtonItem(UIBarButtonSystemItem.Action, null);

            barButton.Clicked += delegate {
                var url = $"მიმღები: შპს \"ეტალონი-განათლება\" მიმღების საიდენტიფიკაციო კოდი: 404561979 სს ბანკი \"თიბისი ბანკი\" TBCBGE22 ანგარიშის ნომერი: GE82TB7994 6360 8010 0007 www.izrune.ge თარიღი: {DateTime.Now.ToString("dd/MM/yyyy")}";

                if (!string.IsNullOrEmpty(url) && !string.IsNullOrWhiteSpace(url))
                {
                    this.ShareUrl(url);
                }
            };

            this.NavigationItem.RightBarButtonItem = barButton;

            numberCopyBttn.TouchUpInside += delegate {
                UIPasteboard.General.String = "GE82TB7994636080100007";
                numberCopyBttn.SetTitle("ნომერი დაკოპირებულია", UIControlState.Normal);
            };
        }

        private async Task InitDataAsync()
        {
            CurrentUser = await IZrune.PCL.Helpers.UserControl.Instance.GetCurrentUser();
            profileNumberLbl.Text = $"1. პროფილის ნომერი - {CurrentUser?.id}";
            userNameLbl.Text = $"2. მომხმარებლის სახელი-გვარი - {CurrentUser?.Name + " " + CurrentUser?.LastName}";
            billLbl.Text = $"3. გადასახდელი თანხა - {SelectedPrice?.price}";
            dateLbl.Text = DateTime.Now.ToString("dd/MM/yyyy");

            userStackView.Hidden = CurrentUser == null;
        }
    }
}
