// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Foundation;
using Izrune.iOS.CollectionViewCells;
using IZrune.PCL.Abstraction.Models;
using IZrune.PCL.Abstraction.Services;
using MPDCiOSPages.ViewControllers;
using UIKit;

namespace Izrune.iOS
{
	public partial class SelectPacketViewController : BaseViewController, IUICollectionViewDelegate, IUICollectionViewDataSource, IUICollectionViewDelegateFlowLayout
	{
		public SelectPacketViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("SelectPacketStoryboardId");

        private int SelectedPriceIndex;

        private List<IPrice> PriceList;
        public int SchoolId;

        public async override void ViewDidLoad()
        {
            base.ViewDidLoad();

            CollectionViewSettings();

            await LoadDataAsync();
        }

        private async Task LoadDataAsync()
        {
            ShowLoading();
            //TODO ProceList = ?

            var service = ServiceContainer.ServiceContainer.Instance.Get<IUserServices>();

            var data = (await service.GetPromoCodeAsync(SchoolId.ToString()));

            PriceList = data.Prices?.ToList();

            packetCollectionView.ReloadData();

            EndLoading();
        }
        private void CollectionViewSettings()
        {
            packetCollectionView.Delegate = this;
            packetCollectionView.DataSource = this;

            packetCollectionView.RegisterNibForCell(PacketCollectionViewCell.Nib, PacketCollectionViewCell.Identifier);
        }

        public UICollectionViewCell GetCell(UICollectionView collectionView, NSIndexPath indexPath)
        {
            var cell = packetCollectionView.DequeueReusableCell(PacketCollectionViewCell.Identifier, indexPath) as PacketCollectionViewCell;

            cell.PriceSelected = (priice) =>
            {

            };

            if (indexPath.Row == SelectedPriceIndex)
                cell.InitData(null, true);
            else
                cell.InitData(null);
            return cell;

        }

        public nint GetItemsCount(UICollectionView collectionView, nint section)
        {
            return PriceList?.Count?? 0 ;
        }

        [Export("collectionView:layout:sizeForItemAtIndexPath:")]
        public CoreGraphics.CGSize GetSizeForItem(UICollectionView collectionView, UICollectionViewLayout layout, NSIndexPath indexPath)
        {
            return new CoreGraphics.CGSize(collectionView.Frame.Width, 70);
        }

    }
}
