// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using Izrune.iOS.CollectionViewCells;
using IZrune.PCL.Abstraction.Models;
using MPDC.iOS.Utils;
using UIKit;

namespace Izrune.iOS
{
	public partial class SelectSchoolViewController : UIViewController, IUICollectionViewDelegate, IUICollectionViewDataSource, IUICollectionViewDelegateFlowLayout
	{
		public SelectSchoolViewController (IntPtr handle) : base (handle)
		{
		}

        public List<ISchool> SchoolList;

        public Action<ISchool> SchoolSelected { get; set; }

        public static readonly NSString StoryboardId = new NSString("SelectSchoolStoryboardId");

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InitCollectionView();


        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            schoolCollectionView.ReloadData();
        }
        public UICollectionViewCell GetCell(UICollectionView collectionView, NSIndexPath indexPath)
        {
            var cell = schoolCollectionView.DequeueReusableCell(SelectSchoolCollectionViewCell.Identifier, indexPath) as SelectSchoolCollectionViewCell;

            var data = SchoolList?[indexPath.Row];

            cell.SchoolSelected = (school) =>
            {
                SchoolSelected?.Invoke(school);
                this.NavigationController.PopViewController(true);
            };

            cell.InitData(data);

            return cell;
        }

        public nint GetItemsCount(UICollectionView collectionView, nint section)
        {
            return SchoolList?.Count ?? 0;
        }

        [Export("collectionView:layout:sizeForItemAtIndexPath:")]
        public CoreGraphics.CGSize GetSizeForItem(UICollectionView collectionView, UICollectionViewLayout layout, NSIndexPath indexPath)
        {
            var titleHeight = SchoolList?[indexPath.Row].title.GetStringHeight((float)collectionView.Frame.Width, 15, 15);
            return new CoreGraphics.CGSize(collectionView.Frame.Width, (System.nfloat)(titleHeight + 30));
        }

        private void InitCollectionView()
        {
            schoolCollectionView.RegisterNibForCell(SelectSchoolCollectionViewCell.Nib, SelectSchoolCollectionViewCell.Identifier);

            schoolCollectionView.Delegate = this;
            schoolCollectionView.DataSource = this;

            schoolCollectionView.ReloadData();
        }
    }
}
