// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using Foundation;
using Izrune.iOS.Utils;
using IZrune.PCL.Abstraction.Models;
using IZrune.PCL.Abstraction.Services;
using IZrune.PCL.Enum;
using IZrune.PCL.Helpers;
using MpdcViewExtentions;
using UIKit;

namespace Izrune.iOS
{
	public partial class SmsVerificationViewController : UIViewController
	{
		public SmsVerificationViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("SmsVerificationStoryboardId");
        private IParent parent;
        private int code;

        public IStudent SelectedStudent;

        public async override void ViewDidLoad()
        {
            base.ViewDidLoad();

            this.NavigationItem.BackBarButtonItem = new UIBarButtonItem("", UIBarButtonItemStyle.Plain, null);

            InitUI();

            parent = await UserControl.Instance.GetCurrentUser();
            
            //code = await ServiceContainer.ServiceContainer.Instance.Get<IQuezServices>().GetSmsCodeAsync(parent.id);
            smsTf.EditingDidEnd += (s,e) => {
                //TODO

            };

            confirmBtn.TouchUpInside += async delegate {

                try
                {
                    if(string.IsNullOrEmpty(smsTf.Text) || string.IsNullOrWhiteSpace(smsTf.Text))
                    {
                        var alert = UIAlertController.Create("ყურადღება", "გთხოვთ ჩაწეროთ SMS კოდი", UIAlertControllerStyle.Alert);
                        alert.AddAction(UIAlertAction.Create("დახურვა", UIAlertActionStyle.Default, null));
                        this.PresentViewController(alert, true, null);
                    }
                    else
                    {
                        if (Convert.ToInt32(smsTf.Text) == code)
                        {
                            CheckSms(true);
                            await Task.Delay(200);

                            GoToChooseTime();
                        }
                        else
                            CheckSms(false);
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            };

            getCodeBtn.TouchUpInside += async delegate
            {
                code = await ServiceContainer.ServiceContainer.Instance.Get<IQuezServices>().GetSmsCodeAsync(parent.id);
            };
        }

        private void CheckSms(bool isValid)
        {

            smsTextLbl.Text = isValid ? "SMS კოდი სწორია" : "SMS კოდი არ არის სწორი";
            smsTf.Layer.BorderColor = isValid ? AppColors.Succesful.CGColor : AppColors.ErrorTitle.CGColor;

            smsTf.TextColor = UIColor.White;
            smsTextLbl.TextColor = isValid ? AppColors.Succesful : AppColors.ErrorTitle;
            smsTf.BackgroundColor = isValid ? AppColors.LightGreen : AppColors.LightRed;
            smsTf.AddShadowToView(5, 25, 0.8f, isValid ? AppColors.GreenShadow : AppColors.RedShadow);
        }

        private void InitUI()
        {
            smsTf.MakeRoundedTextField(25, UIColor.FromRGB(243, 243, 243));
            smsTf.TextAlignment = UITextAlignment.Center;
            smsTf.Layer.BorderWidth = 2;
            smsTf.Layer.BorderColor = UIColor.White.CGColor;

            smsShadowView.AddShadowToView(2, 25, 0.3f, UIColor.FromRGBA(0, 0, 0, 0.25f));
            confirmBtn.AddShadowToView(2, 25, 0.4f, AppColors.Tint);
            getCodeBtn.AddShadowToView(2, 25, 0.4f, UIColor.FromRGBA(99, 222, 255, 153));
        }

        private void GoToChooseTime()
        {
            var chooseTimeVc = Storyboard.InstantiateViewController(ChooseTimeViewController.StoryboardId) as ChooseTimeViewController;
            chooseTimeVc.IsSumtTest = true;
            chooseTimeVc.SelectedStudent = SelectedStudent;
            chooseTimeVc.SelectedCategory = QuezCategory.QuezExam;

            this.NavigationController.PushViewController(chooseTimeVc, true);
        }
    }
}
