// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Foundation;
using FPT.Framework.iOS.UI.DropDown;
using Izrune.iOS.Utils;
using IZrune.PCL.Abstraction.Models;
using IZrune.PCL.Helpers;
using MpdcViewExtentions;
using UIKit;

namespace Izrune.iOS
{
	public partial class StudentStatisticViewController : UIViewController
	{
		public StudentStatisticViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("StudentStatisticStoryboardId");


        DropDown CurentStudentDP = new DropDown();

        IStudent CurrentStudent;

        private List<IStudent> Students;
        private int currentStudentIndex;

        public async override void ViewDidLoad()
        {
            base.ViewDidLoad();

            await LoadDataAsync();

            View.LayoutIfNeeded();

            InitUI();

            InitGestures();
        }

        private async Task LoadDataAsync()
        {
            Students = (await UserControl.Instance.GetCurrentUserStudents())?.ToList();

            CurrentStudent = Students?[0];

        }

        private void InitUI()
        {

            initView(diplomeView, diplomeShadow);
            initView(sumTestsView, sumShadow);
            initView(exTestView, exShadow);

            paymentHostoryBtn.Layer.CornerRadius = 25;
        }

        private void initView(UIView view, UIView viewForShadow)
        {
            view.Layer.BorderWidth = 3;
            view.Layer.BorderColor = UIColor.White.CGColor;
            view.Layer.CornerRadius = 25;
            view.ApplyGradient(AppColors.PurpleGradient);

            viewForShadow.AddShadowToView(10, 25, 0.8f, AppColors.TitleColor);
        }

        private void InitGestures()
        {
            if (diplomeView.GestureRecognizers == null || diplomeView.GestureRecognizers?.Length == 0)
            {
                diplomeView.AddGestureRecognizer(new UITapGestureRecognizer(() => {
                    //TODO

                }));
            }

            if (sumTestsView.GestureRecognizers == null || sumTestsView.GestureRecognizers?.Length == 0)
            {
                sumTestsView.AddGestureRecognizer(new UITapGestureRecognizer(() => {

                    //TODO
                }));
            }

            if (exTestView.GestureRecognizers == null || exTestView.GestureRecognizers?.Length == 0)
            {
                exTestView.AddGestureRecognizer(new UITapGestureRecognizer(() => {

                    //TODO
                }));
            }

            paymentHostoryBtn.TouchUpInside += delegate {

                //TODO
            };
        }

        private void InitDropDowns()
        {
            SetupDropDown(CurentStudentDP, currentStudentView, currentStudentLbl);

            var studentsArray = Students?.Select(x => x.Name)?.ToArray();
            CurentStudentDP.DataSource = studentsArray;


            CurentStudentDP.SelectionAction = (nint index, string name) =>
            {
                if (currentStudentIndex != index)
                {
                    CurrentStudent = Students?[(int)index];
                }
            };

        }

        private void SetupDropDown(DropDown dropDown, UIView viewForDpD, UILabel dropDownLbl)
        {
            dropDown.AnchorView = new WeakReference<UIView>(viewForDpD);
            dropDown.BottomOffset = new CoreGraphics.CGPoint(0, viewForDpD.Bounds.Height);
            dropDown.Width = View.Frame.Width;
            dropDown.Direction = Direction.Bottom;
        }

        private void InitDropDownUI(DropDown dropDown)
        {
            dropDown.BackgroundColor = UIColor.FromRGB(243, 243, 243);
            dropDown.SelectionBackgroundColor = AppColors.TitleColor;
            DPDConstants.UI.TextColor = AppColors.TitleColor;
            DPDConstants.UI.SelectedTextColor = UIColor.White;

            dropDown.TextFont = UIFont.FromName("BPG Mrgvlovani Caps 2010", 15);
            dropDown.ClipsToBounds = true;
            dropDown.Layer.CornerRadius = 20;
        }
    }
}
