// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Izrune.iOS
{
	public partial class SuccesViewController : UIViewController
	{
		public SuccesViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("SuccesViewControllerStoryboardId");

        public string TitleText { get; set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            titleLbl.Text = TitleText;

            loginBtn.TouchUpInside += delegate {
                //TODO
            };
        }
    }
}
