// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cavea.iOS.Utils;
using Foundation;
using Izrune.iOS.CollectionViewCells;
using IZrune.PCL.Abstraction.Models;
using IZrune.PCL.Abstraction.Services;
using UIKit;

namespace Izrune.iOS
{
	public partial class TestViewController : UIViewController, IUICollectionViewDelegate, IUICollectionViewDataSource, IUICollectionViewDelegateFlowLayout
	{
		public TestViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("TestViewControllerStoryboardId");

        List<IQuestion> Questions;

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InitCollectionView();

            skipQuestionBtn.Layer.CornerRadius = 20;

            skipQuestionBtn.TouchUpInside += delegate {

                //var indexPath = questionCollectionView.IndexPathsForVisibleItems[0];

                //var currIndex = indexPath.Row;

                //if(currIndex < 6)
                //{
                //    questionCollectionView.ScrollToItem(NSIndexPath.FromItemSection(currIndex+1, 0), UICollectionViewScrollPosition.Right, true);
                //};

                questionCollectionView.ReloadData();
            };
        }

        private async Task LoadDataAsync()
        {
            var testService = ServiceContainer.ServiceContainer.Instance.Get<IQuezServices>();

            var data = (await testService.GetQuestionsAsync(1, IZrune.PCL.Enum.QuezCategory.QuezTest))?.ToList();

            Questions = data;
        }

        private void InitCollectionView()
        {
            questionCollectionView.RegisterNibForCell(TestCollectionViewCell.Nib, TestCollectionViewCell.Identifier);

            questionCollectionView.Delegate = this;
            questionCollectionView.DataSource = this;
        }

        public UICollectionViewCell GetCell(UICollectionView collectionView, NSIndexPath indexPath)
        {
            var cell = questionCollectionView.DequeueReusableCell(TestCollectionViewCell.Identifier, indexPath) as TestCollectionViewCell;

            //cell.InitData();
            return cell;
        }

        public nint GetItemsCount(UICollectionView collectionView, nint section)
        {
            return 1;
        }

        [Export("collectionView:layout:sizeForItemAtIndexPath:")]
        public CoreGraphics.CGSize GetSizeForItem(UICollectionView collectionView, UICollectionViewLayout layout, NSIndexPath indexPath)
        {

            //TODO Calculate CellHeight

            string title = "asdasdas";

            var titleHeight = title.GetSizeByText(UIFont.FromName("BPG Mrgvlovani Caps 2010", 17));


            return new CoreGraphics.CGSize(collectionView.Frame.Width, collectionView.Frame.Height * 0.5);
        }
    }
}
