// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Izrune.iOS
{
	public partial class AddStudentViewController : UIViewController
	{
		public AddStudentViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("AddStudentViewControllerStoryboardId");


	}
}
