// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Izrune.iOS
{
	public partial class AddStudentViewController : UIViewController
	{
		public AddStudentViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("AddStudentViewControllerStoryboardId");

        public Action SendClicked { get; set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InitGestures();

            InitUI();

            SendClicked = () => SendData();
        }

        private void SendData()
        {
            //TODO
        }

        private void InitUI()
        {
            addNewStudentBtn.Layer.CornerRadius = 25;
            agreeView.Layer.CornerRadius = 17.5f;
            selectedAgreeView.Layer.CornerRadius = 12.5f;
           
        }

        bool IsMarked;

        private void InitGestures()
        {
            addNewStudentBtn.TouchUpInside += delegate {

                //TODO
            };

            if (privacyLbl.GestureRecognizers == null || privacyLbl.GestureRecognizers?.Length == 0)
            {
                privacyLbl.AddGestureRecognizer(new UITapGestureRecognizer(() => {
                    var privacyVc = Storyboard.InstantiateViewController(PrivacyViewController.StoryboardId) as PrivacyViewController;

                    privacyVc.ModalPresentationStyle = UIModalPresentationStyle.OverCurrentContext;
                    this.PresentViewController(privacyVc, true, null);

                }));
            }

            if (agreeView.GestureRecognizers == null || agreeView.GestureRecognizers?.Length == 0)
            {
                agreeView.AddGestureRecognizer(new UITapGestureRecognizer(() => {

                    IsMarked = !IsMarked;
                    selectedAgreeView.Hidden = !IsMarked;
                }));
            }
        }
    }
}
