// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using CoreAnimation;
using Foundation;
using Izrune.iOS.Utils;
using IZrune.PCL.Abstraction.Services;
using MpdcViewExtentions;
using UIKit;

namespace Izrune.iOS
{
	public partial class LogInViewController : UIViewController
	{
		public LogInViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("LogInViewControllerStoryboardId");

        public Action LogedIn { get; set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InitUI();

            InitGestures();
        }

        private void InitGestures()
        {
        
            logInBtn.TouchUpInside += async delegate {
                //ShowLoginAlert();
                try
                {
                    var userName = userNameTextField.Text;
                    var passord = passwordTextField.Text;

                    var loginSevice = ServiceContainer.ServiceContainer.Instance.Get<ILoginServices>();
                    var isLogedIn = (await loginSevice.LoginUser(userName, passord));

                    if(isLogedIn)
                    {

                        //var testVc = Storyboard.InstantiateViewController(StartTestViewController.StoryboardId) as StartTestViewController;
                        //this.NavigationController.PushViewController(testVc, true);
                        LogedIn?.Invoke();
                    }
                }

                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            };

            registrationBtn.TouchUpInside += delegate {

                //TODO
                var registerVc = Storyboard.InstantiateViewController(ParentRegistrationViewController.StoryboardId) as ParentRegistrationViewController;


                this.NavigationItem.BackBarButtonItem = new UIBarButtonItem("", UIBarButtonItemStyle.Plain, null);
                this.NavigationController.PushViewController(registerVc, true);
            };
        }

        private void InitUI()
        {

            logInBtn.ToCardView(25, 10, 0.1f, UIColor.FromRGBA(0,0,0,0));
            registrationBtn.ToCardView(25, 3, 0.2f, AppColors.Tint);

            userNameTextField.MakeRoundedTextField(20.0f, AppColors.TextFieldBackground, 17);
            passwordTextField.MakeRoundedTextField(20.0f, AppColors.TextFieldBackground, 17);

            logInBtn.AddShadowToView(10, 25, 0.8f, AppColors.Succesful);
            registrationBtn.AddShadowToView(10, 25, 0.8f, AppColors.TitleColor);

        }

        private void ShowLoginAlert()
        {
            var alert = UIAlertController.Create("შეცდომა", "მომხმარებელი ან პაროლი არასორია.", UIAlertControllerStyle.Alert);
            alert.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));
            this.PresentViewController(alert, true, null);
        }
    }
}
