// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Izrune.iOS.Utils;
using UIKit;

namespace Izrune.iOS
{
	public partial class LogInViewController : UIViewController
	{
		public LogInViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("LogInViewControllerStoryboardId");

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InitUI();
        }


        private void InitUI()
        {
            loginView.Layer.CornerRadius = 25;
            registrationView.Layer.CornerRadius = 25;

            loginView.BackgroundColor = AppColors.Succesful;
            registrationView.BackgroundColor = AppColors.Tint;

            //var attr = new UIStringAttributes()
            //{
            //    ForegroundColor = AppColors.PlaceHolder,
            //    Font = UIFont.FromName("BPG Mrgvlovani 2010", 14)
            //};

            //userNameTextField.AttributedPlaceholder = new NSAttributedString("სახელი", attr);
        }
    }
}
