// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using Foundation;
using Izrune.iOS.Utils;
using IZrune.PCL.Helpers;
using MPDC.iOS.Utils;
using MpdcViewExtentions;
using UIKit;

namespace Izrune.iOS
{
	public partial class ParentRegSecondViewController : UIViewController
	{
		public ParentRegSecondViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("ParentRegSecondStoryboardId");

        public Action SendClicked { get; set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InitUI();

            SendClicked = () => { SenData(); };
        }

        public bool IsFormFilled()
        {
            var res = (phoneTextField.Text.IsEmtyOrNull() && userNameTextField.Text.IsEmtyOrNull() && passwordTextField.Text.IsEmtyOrNull() && repeatPasswordTextField.Text.IsEmtyOrNull());

            if (res)
                return CheckPassword();
            return res;
        }

        private void InitUI()
        {
            var textFields = textFieldsStackView.Subviews?.Where(x => x is UITextField)?.Select(x => x as UITextField);

            foreach (var item in textFields)
            {
                item.MakeRoundedTextField(20.0f, AppColors.TextFieldBackground, 20);
            }
        }

        private void SenData()
        {
            UserControl.Instance.RegistrationParrentPartTwo(
                phoneTextField.Text,
                emailTextField.Text,
                userNameTextField.Text,
                passwordTextField.Text
                );
        }

        public bool CheckPassword()
        {
            if(passwordTextField.Text != repeatPasswordTextField.Text)
            {
                var alertVc = UIAlertController.Create("ყურადღება!", "პაროლები არ ემთხვევა ერთმანეთს", UIAlertControllerStyle.Alert);
                alertVc.AddAction(UIAlertAction.Create("დახურვა", UIAlertActionStyle.Default, null));
                this.PresentViewController(alertVc, true, null);
                return false;
            }

            return true;
        }
    }
}