// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Izrune.iOS.Utils;
using MpdcViewExtentions;
using UIKit;

namespace Izrune.iOS
{
	public partial class PasswordRecoveryViewController : UIViewController
	{
		public PasswordRecoveryViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("PasswordRecoveryStoryboardId");

        public string TitleText { get; set; }

        public string ErrorText { get; set; }

        public bool IsPassworPage = true;

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InitUI();

            sendBtn.TouchUpInside += delegate {
                ShowError(true);
                this.View.EndEditing(true);

                var succsessVc = Storyboard.InstantiateViewController(SuccesViewController.StoryboardId) as SuccesViewController;
                succsessVc.TitleText = IsPassworPage ? "პაროლი გაგზავნილია მითითებულ ნომერზე" : "მომხმარებლის სახელი გაგზავნილია მითითებულ ტელეფონის ნომერზე";

                this.AddVcInView(this.View, succsessVc);
            };

            backBtn.TouchUpInside += delegate {
                this.NavigationController.PopViewController(true);
            };
        }


        private void InitUI()
        {
            sendBtn.ToCardView(25, 3, 0.2f, AppColors.Tint);
            backBtn.Layer.CornerRadius = 25;

            phoneTextField.MakeRoundedTextField(20.0f, AppColors.TextFieldBackground, 17);

            titleLbl.Text = IsPassworPage? "პაროლის აღდგენა" : "მომხმარებლის სახელის აღდგენა";


        }

        private void ShowError(bool isError)
        {
            errorLbl.Hidden = !isError;

            phoneTextField.AddBorderToTextField(isError? AppColors.ErrorTitle : UIColor.Clear);

            phoneTextField.TextColor = isError ? AppColors.ErrorTitle : UIColor.Black;
        }
    }
}
