// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Izrune.iOS.Utils;
using MpdcViewExtentions;
using UIKit;

namespace Izrune.iOS
{
	public partial class PasswordRecoveryViewController : UIViewController
	{
		public PasswordRecoveryViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("PasswordRecoveryStoryboardId");

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }


        private void InitUI()
        {
            sendView.ToCardView(25, 3, 0.2f, AppColors.Tint);
            backView.Layer.CornerRadius = 25;
        }
    }
}
