// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Izrune.iOS
{
	public partial class StudentRegFirstViewController : UIViewController
	{
		public StudentRegFirstViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("StudentRegFirstStoryboardId");

        public Action SendClicked { get; set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }


    }
}
