// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Globalization;
using System.Linq;
using Foundation;
using Izrune.iOS.Utils;
using IZrune.PCL.Abstraction.Models;
using IZrune.PCL.Helpers;
using IZrune.PCL.Implementation.Models;
using MPDC.iOS.Utils;
using MpdcViewExtentions;
using UIKit;

namespace Izrune.iOS
{
	public partial class StudentRegFirstViewController : UIViewController
	{
		public StudentRegFirstViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("StudentRegFirstStoryboardId");

        CultureInfo cultureInfo = new CultureInfo("ka-GE");

        private DateTime date = default(DateTime);

        public Action SendClicked { get; set; }

        public IStudent Student;

        public Action StudentSelected { get; set; }
        public Action AddStudentClicked { get; set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            this.NavigationItem.BackBarButtonItem = new UIBarButtonItem("", UIBarButtonItemStyle.Plain, null);

            InitUI();

            InitGestures();

            SendClicked = () => { SenData(); };

            StudentSelected = () =>
            {
                Student = new Student()
                {
                    Name = firstNameTf.Text,
                    LastName = lastNameLTf.Text,
                    Bdate = new DateTime(int.Parse(yearTextField.Text), int.Parse(monthTextField.Text), int.Parse(dayTextField.Text)),
                    PersonalNumber = privateNumberTf.Text,
                    Phone = phoneTf.Text,
                    Email = emailTf.Text
                };
            };
        }

        public bool IsFormFilled()
        {
            var res = (firstNameTf.Text.IsEmtyOrNull() && lastNameLTf.Text.IsEmtyOrNull() && date.Year > 0001 && privateNumberTf.Text.IsEmtyOrNull());
            return res;
        }


        private void InitGestures()
        {
            transparentTextField.EditingDidBegin += (sender, e) =>
            {
                ShowDatePicker();
            };
        }

        private void InitUI()
        {
            var textFields = textFieldsStackView.Subviews?.Where(x => x is UITextField)?.Select(x => x as UITextField);

            foreach (var item in textFields)
            {
                item.MakeRoundedTextField(20.0f, AppColors.TextFieldBackground, 20);
            }

            transparentTextField.MakeRoundedTextField(20.0f, UIColor.Clear, 10);
            dayTextField.MakeRoundedTextField(20.0f, AppColors.TextFieldBackground, 0);
            monthTextField.MakeRoundedTextField(20.0f, AppColors.TextFieldBackground, 0);
            yearTextField.MakeRoundedTextField(20.0f, AppColors.TextFieldBackground, 0);
        }

        private void ShowDatePicker()
        {
            var datePicker = new UIDatePicker();

            datePicker.Mode = UIDatePickerMode.Date;
            datePicker.Locale = new NSLocale("ka-GE");

            var toolBar = new UIToolbar();
            toolBar.SizeToFit();
            var doneButton = new UIBarButtonItem("არჩევა", UIBarButtonItemStyle.Plain, (sender, e) => {

                date = datePicker.Date.NSDateToDateTime();
                InitDate(date);
                this.View.EndEditing(true);
            });

            var spaceButton = new UIBarButtonItem(UIBarButtonSystemItem.FlexibleSpace, null, null);

            var cancelButton = new UIBarButtonItem("დახურვა", UIBarButtonItemStyle.Plain, (s, e) => { this.View.EndEditing(true); });

            toolBar.SetItems(new UIBarButtonItem[] { cancelButton, spaceButton, doneButton }, false);

            transparentTextField.InputAccessoryView = toolBar;
            transparentTextField.InputView = datePicker;
        }

        private void SenData()
        {
            UserControl.Instance.RegistrationStudentPartOne(
                firstNameTf.Text,
                lastNameLTf.Text,
                date,
                privateNumberTf.Text,
                phoneTf.Text,
                emailTf.Text
                );
        }

        private void InitDate(DateTime _date)
        {
            dayTextField.Text = _date.Day.ToString();
            monthTextField.Text = _date.ToString("MMMM", cultureInfo);
            yearTextField.Text = _date.Year.ToString();
        }
    }
}
