// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using FPT.Framework.iOS.UI.DropDown;
using Izrune.iOS.Utils;
using MpdcViewExtentions;
using MPDC.iOS.Utils;
using System.Collections.Generic;
using IZrune.PCL.Abstraction.Models;
using System.Linq;

namespace Izrune.iOS
{
	public partial class StudentRegSecondViewController : UIViewController
	{
		public StudentRegSecondViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("StudentRegSecondStoryboardId");

        DropDown CityDpD = new DropDown();
        DropDown SchoolDpD = new DropDown();
        DropDown ClassDpD = new DropDown();

        public Action SendClicked { get; set; }
        public string[] schoolArrray { get; private set; }

        public List<IRegion> CityList;

        private int SelectedCityindex;
        private string[] cityArray;

        private SelectSchoolViewController ScholVc;

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            ScholVc = Storyboard.InstantiateViewController(SelectSchoolViewController.StoryboardId) as SelectSchoolViewController;

            ScholVc.SchoolSelected = (school) =>
            {
                schoolLbl.Text = school.title;
            };

            villageTextField.MakeRoundedTextField(20.0f, AppColors.TextFieldBackground, 20);
            DropDownInit();

            if (selectSchoolView.GestureRecognizers == null || selectSchoolView.GestureRecognizers?.Length == 0)
            {
                selectSchoolView.AddGestureRecognizer(new UITapGestureRecognizer(() => {

                    this.NavigationController.PushViewController(ScholVc, true);
                }));
            }
        }

        private void DropDownInit()
        {
            SetupDropDownGesture(CityDpD, cityView);
            SetupDropDownGesture(ClassDpD, classView);

            SetupDropDown(CityDpD, cityView, cityLbl);
            SetupDropDown(ClassDpD, classView, classLbl);

            InitDropDowns();
        }

        private void InitDropDowns()
        {
            SetupDropDown(CityDpD, cityView, cityLbl);
            SetupDropDown(ClassDpD, classView, classLbl);

            SetupDropDownGesture(CityDpD, cityView);
            SetupDropDownGesture(ClassDpD, classView);

            cityArray = CityList?.Select(x => x.title)?.ToArray();
            CityDpD.DataSource = cityArray;

            CityDpD.SelectionAction = (nint index, string name) =>
            {
                //TODO
                SelectedCityindex = (int)index;

                selectSchoolView.UserInteractionEnabled = true;
                ScholVc.SchoolList = CityList?[SelectedCityindex].Schools?.OrderBy(x => x.title)?.ToList();
                cityLbl.Text = name;

            };

             
            SchoolDpD.SelectionAction = (nint index, string name) =>
            {

                classView.UserInteractionEnabled = true;
            };
        }

        private void SetupDropDown(DropDown dropDown, UIView viewForDpD, UILabel dropDownLbl)
        {
            dropDown.AnchorView = new WeakReference<UIView>(viewForDpD);
            dropDown.BottomOffset = new CoreGraphics.CGPoint(0, viewForDpD.Bounds.Height);
            dropDown.Width = View.Frame.Width;
            dropDown.Direction = Direction.Bottom;

            //var array = Students?.Select(x => x.Name + " " + x.LastName)?.ToArray();

            //CityDpD.DataSource = array;

        }

        private void InitDropDownUI(DropDown dropDown)
        {
            dropDown.BackgroundColor = UIColor.FromRGB(243, 243, 243);
            dropDown.SelectionBackgroundColor = AppColors.TitleColor;
            DPDConstants.UI.TextColor = AppColors.TitleColor;
            DPDConstants.UI.SelectedTextColor = UIColor.White;

            dropDown.TextFont = UIFont.FromName("BPG Mrgvlovani Caps 2010", 15);
            dropDown.ClipsToBounds = true;
            dropDown.Layer.CornerRadius = 20;
        }

        private void SetupDropDownGesture(DropDown dropDown, UIView viewforDpD)
        {
            if (viewforDpD.GestureRecognizers == null || viewforDpD.GestureRecognizers?.Length == 0)
            {
                viewforDpD.AddGestureRecognizer(new UITapGestureRecognizer(() =>
                {
                    dropDown.Show();
                    InitDropDownUI(dropDown);
                }));
            }
        }

    }
}
