// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using FPT.Framework.iOS.UI.DropDown;
using Izrune.iOS.Utils;

namespace Izrune.iOS
{
	public partial class StudentRegSecondViewController : UIViewController
	{
		public StudentRegSecondViewController (IntPtr handle) : base (handle)
		{
		}

        DropDown CityDpD = new DropDown();
        DropDown SchoolDpD = new DropDown();
        DropDown ClassDpD = new DropDown();

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InitDropDowns();

        }

        private void InitDropDowns()
        {
            SetupDropDown(CityDpD, cityView, cityLbl);
            SetupDropDown(SchoolDpD, schoolView, schoolLbl);
            SetupDropDown(ClassDpD, classView, classLbl);

            InitDropDownUI(CityDpD);
            InitDropDownUI(SchoolDpD);
            InitDropDownUI(ClassDpD);
        }

        private void SetupDropDown(DropDown dropDown, UIView viewForDpD, UILabel dropDownLbl)
        {
            dropDown.AnchorView = new WeakReference<UIView>(viewForDpD);
            dropDown.BottomOffset = new CoreGraphics.CGPoint(0, viewForDpD.Bounds.Height);
            dropDown.Width = viewForDpD.Frame.Width;
            dropDown.Direction = Direction.Bottom;

            //var array = Students?.Select(x => x.Name + " " + x.LastName)?.ToArray();

            //CityDpD.DataSource = array;

            CityDpD.SelectionAction = (nint index, string name) =>
            {
                //TODO
                dropDownLbl.Text = name;
            };
        }

        private void InitDropDownUI(DropDown dropDown)
        {
            dropDown.BackgroundColor = UIColor.FromRGB(243, 243, 243);
            dropDown.SelectionBackgroundColor = AppColors.TitleColor;
            DPDConstants.UI.TextColor = AppColors.TitleColor;
            DPDConstants.UI.SelectedTextColor = UIColor.White;

            dropDown.TextFont = UIFont.FromName("BPG Mrgvlovani Caps 2010", 15);
            dropDown.ClipsToBounds = true;
            dropDown.Layer.CornerRadius = 20;
        }
    }
}
