// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Izrune.iOS.Utils;
using MpdcViewExtentions;
using UIKit;

namespace Izrune.iOS
{
	public partial class SuccesViewController : UIViewController
	{
		public SuccesViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("SuccesViewControllerStoryboardId");

        public string TitleText { get; set; }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();


            titleLbl.Text = TitleText;

            loginBtn.ToCardView(25, 10, 0.1f, UIColor.FromRGBA(0, 0, 0, 0));
            loginBtn.AddShadowToView(10, 25, 0.8f, AppColors.Succesful);

            checkView.AddShadowToView(10, 30, 0.8f, AppColors.Succesful);

            loginBtn.TouchUpInside += delegate {
                this.NavigationController.PopViewController(true);
            };

        }
    }
}
