// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MpdcViewExtentions;
using System.Linq;
using Izrune.iOS.Utils;

namespace Izrune.iOS
{
	public partial class EditProfileViewController : UIViewController
	{
		public EditProfileViewController (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString StoryboardId = new NSString("EditProfileStoryboardId");

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            this.NavigationItem.BackBarButtonItem = new UIBarButtonItem("", UIBarButtonItemStyle.Plain, null);

            View.LayoutIfNeeded();

            InitUI();

            InitGestures();
        }

        private void InitUI()
        {
        
            initView(parentView, parentShadow);
            initView(studentView, studentShadow);
            initView(passowrdView, passwordShadow);

            addStudentBtn.Layer.CornerRadius = 25;
        }

        private void initView(UIView view, UIView viewForShadow)
        {
            view.Layer.BorderWidth = 3;
            view.Layer.BorderColor = UIColor.White.CGColor;
            view.Layer.CornerRadius = 25;
            view.ApplyGradient(AppColors.PurpleGradient);

            viewForShadow.AddShadowToView(10, 25, 0.8f, AppColors.TitleColor);
        }

        private void InitGestures()
        {
            if(parentView.GestureRecognizers == null || parentView.GestureRecognizers?.Length == 0)
            {
                parentView.AddGestureRecognizer(new UITapGestureRecognizer(() => {
                    var editParentVc = Storyboard.InstantiateViewController(EditParentProfileViewController.StoryboardId) as EditParentProfileViewController;

                    this.NavigationController.PushViewController(editParentVc, true);

                }));
            }

            if (studentView.GestureRecognizers == null || studentView.GestureRecognizers?.Length == 0)
            {
                studentView.AddGestureRecognizer(new UITapGestureRecognizer(() => {

                    //TODO
                }));
            }

            if (passowrdView.GestureRecognizers == null || passowrdView.GestureRecognizers?.Length == 0)
            {
                passowrdView.AddGestureRecognizer(new UITapGestureRecognizer(() => {

                    //TODO
                }));
            }

            addStudentBtn.TouchUpInside += delegate {

                //TODO
            };
        }
    }
}
